
#+++++++++++++++++++++++++++++++++++++++++++++"
# Script Name  : ocfs2ClusterConfigCreate.sh +"
# Written By   : Timmy Babayeju              +"
# From Company : Fujitsu                     +"
# To  Company  : FSA                         +"
#+++++++++++++++++++++++++++++++++++++++++++++"
#!/bin/sh
dos2unix inputAppProperties.*
. inputAppProperties.csv

## This function creates the cluster configuration file
## All the entries are populated from the inputAppProperties.csv
## The function call should be executed on the Nodes consituting the filesystem cluster

createClusterFile(){

echo "#"                 >/etc/ocfs2/cluster.conf
echo "## Generated by script : Author - Timmy Babayeju"                          >>/etc/ocfs2/cluster.conf
echo "#"                 >>/etc/ocfs2/cluster.conf
echo "cluster:"                          >>/etc/ocfs2/cluster.conf
echo "        node_count = $OCFS_NODES_TOTAL"        >>/etc/ocfs2/cluster.conf
echo "        name = $OCFS_CLUSTER_NAME"                 >>/etc/ocfs2/cluster.conf
for (( n = 1; n <= $OCFS_NODES_TOTAL; n++ ))
do
 if [ $n = 1 ]
 then
    echo "node:"        >>/etc/ocfs2/cluster.conf
    echo "        ip_port = 5555"        >>/etc/ocfs2/cluster.conf
    echo "        ip_address = $OCFS_NODE_1_IPADDR"  >>/etc/ocfs2/cluster.conf 
    echo "        number = $n"        >>/etc/ocfs2/cluster.conf
    echo "        name = $OCFS_NODE_1_NAME"        >>/etc/ocfs2/cluster.conf
    echo "        cluster = $OCFS_CLUSTER_NAME"        >>/etc/ocfs2/cluster.conf
 else
    echo "node:"        >>/etc/ocfs2/cluster.conf
    echo "        ip_port = 5555"        >>/etc/ocfs2/cluster.conf
    echo "        ip_address = $OCFS_NODE_2_IPADDR"  >>/etc/ocfs2/cluster.conf 
    echo "        number = $n"        >>/etc/ocfs2/cluster.conf
    echo "        name = $OCFS_NODE_2_NAME"        >>/etc/ocfs2/cluster.conf
    echo "        cluster = $OCFS_CLUSTER_NAME"        >>/etc/ocfs2/cluster.conf
 fi 
done
}

createClusterFile
